INSERT OR REPLACE INTO content_entries (
  id, type, slug, title, excerpt, body_json, status, seo_title,
  seo_description, social_image_url, social_image_alt, primary_query,
  author_name, published_at, created_at, updated_at
) VALUES
(
  '11111111-1111-4111-8111-111111111111',
  'blog',
  'turkish-breakfast-san-francisco',
  'A Guide to Turkish Breakfast in San Francisco',
  'Learn how a traditional Turkish breakfast brings bread, cheeses, olives, eggs, tea and conversation together around one generous table.',
  '[{"type":"paragraph","text":"Turkish breakfast is less about one main dish and more about sharing a table filled with complementary flavors. Warm bread, savory cheeses, olives, vegetables, eggs, preserves, honey and tea arrive together, inviting everyone to taste, pass plates and stay a little longer."},{"type":"heading","level":2,"text":"What makes a Turkish breakfast distinctive?"},{"type":"paragraph","text":"The variety creates the experience. Salty cheese and olives balance sweet honey or preserves. Tomatoes and cucumbers bring freshness, while eggs and freshly baked breads make the meal substantial. Rather than moving through separate courses, guests build each bite according to taste."},{"type":"heading","level":2,"text":"Bread at the center of the table"},{"type":"paragraph","text":"Bread connects the different parts of breakfast. It can carry cheese and herbs, gather a spoonful of egg, or pair with honey. Turkish bakeries also produce savory pastries such as borek, acma and pogaca, each offering a different texture and filling."},{"type":"heading","level":2,"text":"Tea, coffee and conversation"},{"type":"paragraph","text":"Turkish tea is traditionally served throughout breakfast, keeping the table warm and social. Turkish coffee has its own place in the culture and is often enjoyed after food. Both drinks encourage a slower rhythm than a meal designed simply to be eaten on the way somewhere else."},{"type":"heading","level":2,"text":"Enjoy Turkish breakfast at Turquaz"},{"type":"paragraph","text":"At Turquaz in San Francisco, breakfast reflects the same spirit of abundance and gathering. Our menu brings Turkish flavors, bakery traditions and warm hospitality to 1198 Mission Street. Check the current menu for available breakfast dishes and pastries before your visit."},{"type":"list","ordered":false,"items":["Explore the current Turquaz menu online","Reserve a table for breakfast with family or friends","Allow time to share several flavors together"]}]',
  'published',
  'Turkish Breakfast in San Francisco | Turquaz',
  'Discover Turkish breakfast traditions, tea, pastries and shared plates at Turquaz restaurant in San Francisco.',
  'https://www.turquazsf.com/assets/images/dish-feature.jpeg',
  'Turkish breakfast spread with eggs, cheeses, olives, honey and bread at Turquaz',
  'turkish breakfast san francisco',
  'Turquaz',
  '2026-08-20T16:00:00.000Z',
  '2026-08-20T16:00:00.000Z',
  '2026-08-20T16:00:00.000Z'
),
(
  '22222222-2222-4222-8222-222222222222',
  'blog',
  'turkish-dishes-and-ingredients',
  'Turkish Dishes and Ingredients to Know',
  'Explore the ingredients and cooking traditions behind meze, kebabs, pide, lentil soup, baklava and other Turkish favorites.',
  '[{"type":"paragraph","text":"Turkish cooking reflects many regions, climates and generations of home and restaurant kitchens. Vegetables, grains, legumes, yogurt, herbs, olive oil, grilled meats, breads and pastries appear in combinations that can feel both comforting and remarkably varied."},{"type":"heading","level":2,"text":"Start with meze"},{"type":"paragraph","text":"Meze are small dishes made for sharing. Hummus, spicy ezme, yogurt-based dips, stuffed grape leaves, roasted eggplant and pickled vegetables can open a meal with contrasting textures and temperatures. Ordering several allows the table to experience a wider range of flavors."},{"type":"heading","level":2,"text":"Kebabs and the grill"},{"type":"paragraph","text":"Turkish kebabs are not one single recipe. Adana kebab uses seasoned minced meat, while shish preparations place marinated pieces of meat or vegetables on skewers. Kofte are seasoned meatballs shaped for the grill. Each style depends on careful seasoning, heat and timing."},{"type":"heading","level":2,"text":"Pide, lahmacun and baked specialties"},{"type":"paragraph","text":"Pide is a boat-shaped Turkish flatbread baked with toppings such as cheese, spinach or seasoned meat. Lahmacun is thinner and crisp, topped with a finely chopped savory mixture. Borek and other bakery items use layered or shaped doughs for flaky, tender results."},{"type":"heading","level":2,"text":"Everyday ingredients with depth"},{"type":"list","ordered":false,"items":["Eggplant, tomatoes, peppers and leafy herbs","Lentils, chickpeas, rice and bulgur","Yogurt, cheeses and butter","Olive oil, lemon, sumac and warm spices","Pistachios, walnuts, honey and pastry"]},{"type":"heading","level":2,"text":"Discover the menu at Turquaz"},{"type":"paragraph","text":"The Turquaz menu in San Francisco includes cold and hot meze, soups and salads, bowls, grilled plates, flatbreads, bakery items, desserts and coffee. Availability and prices can change, so the live menu is the best source when planning your meal."}]',
  'published',
  'Turkish Dishes and Ingredients | Turquaz SF',
  'Learn about Turkish meze, kebabs, pide, lentils, yogurt, eggplant, baklava and more from Turquaz in San Francisco.',
  'https://www.turquazsf.com/assets/images/dish-feast.jpeg',
  'A shared table of Turkish meze, salads, bread and grilled dishes at Turquaz',
  'turkish dishes and ingredients',
  'Turquaz',
  '2026-08-21T16:00:00.000Z',
  '2026-08-21T16:00:00.000Z',
  '2026-08-21T16:00:00.000Z'
),
(
  '33333333-3333-4333-8333-333333333333',
  'blog',
  'turkish-coffee-and-tea-culture',
  'Turkish Coffee and Tea: A Culture of Hospitality',
  'Discover why Turkish coffee and tea are closely connected to hospitality, conversation and the rhythm of a shared meal.',
  '[{"type":"paragraph","text":"In Turkish hospitality, a hot drink is often an invitation to pause. Tea and coffee are served in different ways, yet both create space for conversation and connection before, during or after food."},{"type":"heading","level":2,"text":"Turkish tea throughout the day"},{"type":"paragraph","text":"Turkish tea is commonly brewed strong and served in small, curved glasses. Guests can adjust its intensity and sweetness to taste. Refills make tea a companion to breakfast, a work break, an afternoon visit or an evening conversation."},{"type":"heading","level":2,"text":"What makes Turkish coffee different?"},{"type":"paragraph","text":"Turkish coffee is prepared from very finely ground coffee and served unfiltered in a small cup. The method creates a concentrated drink with a distinctive body. It is meant to be sipped slowly, allowing the grounds to settle at the bottom."},{"type":"heading","level":2,"text":"Coffee after a meal"},{"type":"paragraph","text":"Because Turkish coffee is small and intense, it can provide a satisfying close to a meal. A sweet pastry such as baklava offers a complementary contrast, while a glass of water refreshes the palate."},{"type":"heading","level":2,"text":"Hospitality is the essential ingredient"},{"type":"quote","text":"The meaning of the cup comes from the welcome around it."},{"type":"paragraph","text":"Methods and serving pieces matter, but hospitality gives both drinks their cultural role. Offering tea or coffee tells a guest that there is time for them. At Turquaz, coffee, bakery and dining come together in that same welcoming spirit."}]',
  'published',
  'Turkish Coffee and Tea Culture | Turquaz SF',
  'Learn how Turkish coffee and tea bring hospitality, conversation and tradition to the table at Turquaz in San Francisco.',
  'https://www.turquazsf.com/assets/images/gallery-2.jpeg',
  'Coffee and bar area inside Turquaz restaurant in San Francisco',
  'turkish coffee san francisco',
  'Turquaz',
  '2026-08-22T16:00:00.000Z',
  '2026-08-22T16:00:00.000Z',
  '2026-08-22T16:00:00.000Z'
),
(
  '44444444-4444-4444-8444-444444444444',
  'blog',
  'mission-district-dining-plan',
  'Planning a Meal Near San Francisco’s Mission District',
  'A practical guide to planning breakfast, lunch, dinner or a group meal near the Mission District and central San Francisco.',
  '[{"type":"paragraph","text":"A good San Francisco dining plan starts with the occasion. A quick lunch has different needs from a long family dinner, while a group gathering benefits from advance planning. Turquaz is located at 1198 Mission Street, close to the Civic Center side of the Mission corridor."},{"type":"heading","level":2,"text":"Choose the right time for your visit"},{"type":"paragraph","text":"Breakfast offers a relaxed way to share pastries, eggs, tea and coffee. Lunch works well for bowls, salads, flatbreads and grilled plates. Dinner invites a broader spread of meze and dishes for the table. Review the current hours through the restaurant or its verified business listing before traveling."},{"type":"heading","level":2,"text":"Plan around the table"},{"type":"paragraph","text":"For a group, think about dietary preferences, how many dishes everyone wants to share and whether the occasion needs extra time. Turquaz serves a varied Turkish and Mediterranean menu with vegetable dishes, meze, salads, grilled plates, breads and desserts. Ask the restaurant directly about current ingredients and accommodations."},{"type":"heading","level":2,"text":"Reserve before a busy meal period"},{"type":"paragraph","text":"A reservation helps the team prepare for your party and reduces uncertainty during popular periods. The Turquaz website accepts reservations for up to 15 guests. Larger groups can contact the restaurant by phone to discuss options."},{"type":"heading","level":2,"text":"Build a complete San Francisco outing"},{"type":"paragraph","text":"The central location makes it possible to pair a meal with nearby arts, culture, shopping or an event. Check transit and venue information on the day of your visit because schedules and street conditions can change."},{"type":"list","ordered":true,"items":["Review the live menu","Confirm current hours","Reserve for your party size","Allow time for shared dishes and dessert"]}]',
  'published',
  'Mission District Dining Plan | Turquaz San Francisco',
  'Plan breakfast, lunch, dinner or a group meal near San Francisco’s Mission District at Turquaz on Mission Street.',
  'https://www.turquazsf.com/assets/images/about-interior.jpeg',
  'Dining room interior at Turquaz on Mission Street in San Francisco',
  'mission district dining',
  'Turquaz',
  '2026-08-23T16:00:00.000Z',
  '2026-08-23T16:00:00.000Z',
  '2026-08-23T16:00:00.000Z'
),
(
  '55555555-5555-4555-8555-555555555555',
  'local_page',
  'turkish-restaurant',
  'Turkish and Mediterranean Restaurant in San Francisco',
  'Visit Turquaz on Mission Street for Turkish and Mediterranean breakfast, lunch, dinner, pastries and coffee in San Francisco.',
  '[{"type":"paragraph","text":"Turquaz brings Turkish cooking, Mediterranean ingredients, bakery traditions and warm hospitality together at 1198 Mission Street in San Francisco. Guests can join us for breakfast, lunch or dinner, meet over coffee, or share a table of meze and grilled dishes."},{"type":"heading","level":2,"text":"Turkish food for different moments of the day"},{"type":"paragraph","text":"The menu moves from Turkish breakfast and fresh pastries to soups, salads, bowls, pide, kebabs and shareable feasts. Coffee, tea and desserts offer a reason to stay after the main meal. Because selections and prices may change, our live menu is the most current guide."},{"type":"heading","level":2,"text":"A table designed for sharing"},{"type":"paragraph","text":"Turkish dining is especially rewarding when several dishes meet at the center of the table. Begin with meze, add bread or a flatbread, and choose grilled plates or vegetable dishes to share. This format gives each guest room to discover different textures and flavors."},{"type":"heading","level":2,"text":"Visit Turquaz on Mission Street"},{"type":"list","ordered":false,"items":["Address: 1198 Mission St, San Francisco, CA 94102","Phone: +1 415-791-0770","Turkish and Mediterranean cuisine","Breakfast, lunch and dinner reservations","Online ordering and catering options"]},{"type":"heading","level":2,"text":"Reserve or order online"},{"type":"paragraph","text":"Use the Turquaz website to reserve a table for up to 15 guests or follow the online-ordering link for current pickup and delivery choices. For larger parties, catering or private-event questions, contact the restaurant directly."}]',
  'published',
  'Turkish Restaurant in San Francisco | Turquaz',
  'Visit Turquaz, a Turkish and Mediterranean restaurant on Mission Street in San Francisco. View the menu, reserve or order online.',
  'https://www.turquazsf.com/assets/images/hero.jpeg',
  'Turquaz Turkish and Mediterranean restaurant in San Francisco',
  'turkish restaurant san francisco',
  'Turquaz',
  '2026-08-24T16:00:00.000Z',
  '2026-08-24T16:00:00.000Z',
  '2026-08-24T16:00:00.000Z'
),
(
  '66666666-6666-4666-8666-666666666666',
  'local_page',
  'turkish-catering-and-group-dining',
  'Turkish Catering and Group Dining in San Francisco',
  'Plan a San Francisco gathering with shareable Turkish and Mediterranean dishes, catering options and group dining at Turquaz.',
  '[{"type":"paragraph","text":"Food for a group should be generous, easy to share and suited to the occasion. Turquaz offers Turkish and Mediterranean flavors for office meals, family celebrations, community gatherings and other San Francisco events."},{"type":"heading","level":2,"text":"Build a shareable Turkish menu"},{"type":"paragraph","text":"Meze, salads, rice or bulgur, breads, grilled meats, vegetable dishes and pastries can be combined into a varied spread. A shared format lets guests explore several flavors and makes the meal feel connected rather than individually packaged."},{"type":"heading","level":2,"text":"Plan for your group"},{"type":"list","ordered":true,"items":["Estimate the guest count and serving time","Share dietary needs and ingredient questions","Choose pickup, delivery or an in-restaurant meal","Confirm serving equipment and setup needs","Place the order with enough preparation time"]},{"type":"heading","level":2,"text":"Office lunches and team meals"},{"type":"paragraph","text":"For workplace gatherings, bowls, salads, meze, breads and grilled plates can create a flexible lunch with familiar and new flavors. Confirm the final menu, quantities and fulfillment details with the restaurant or the linked catering platform."},{"type":"heading","level":2,"text":"Family celebrations and social gatherings"},{"type":"paragraph","text":"A Turkish table naturally supports conversation and sharing. A sequence of meze, warm dishes, grilled selections and dessert can suit birthdays, reunions and informal celebrations. Contact Turquaz early when the group is large or the timing is fixed."},{"type":"heading","level":2,"text":"Start your catering request"},{"type":"paragraph","text":"Turquaz provides online catering options and direct contact for custom requests. Tell us the date, approximate guest count, preferred service time and any dietary questions so the team can guide you toward current choices."}]',
  'published',
  'Turkish Catering San Francisco | Turquaz',
  'Explore Turkish and Mediterranean catering and group dining in San Francisco from Turquaz. Plan office meals, celebrations and events.',
  'https://www.turquazsf.com/assets/images/dish-feast.jpeg',
  'Shareable Turkish feast suitable for catering and group dining from Turquaz',
  'turkish catering san francisco',
  'Turquaz',
  '2026-08-25T16:00:00.000Z',
  '2026-08-25T16:00:00.000Z',
  '2026-08-25T16:00:00.000Z'
);
