INSERT OR IGNORE INTO content_entries (
  id, type, slug, title, excerpt, body_json, status, seo_title,
  seo_description, social_image_url, social_image_alt, primary_query,
  author_name, published_at, created_at, updated_at
) VALUES
(
  '77777777-7777-4777-8777-777777777777',
  'blog',
  'what-to-order-first-turkish-meal',
  'What to Order for Your First Turkish Meal',
  'A practical way to build a first Turkish meal with meze, bread, grilled dishes, vegetables, dessert, coffee and tea.',
  '[{"type":"html","html":"<p>A first Turkish meal is easiest to understand as a table that develops in layers. Instead of choosing one isolated entree, begin with contrasting small plates, add bread, select a warm dish or something from the grill, and leave room for dessert or coffee. The result can be as quick or as leisurely as the occasion requires.</p><h2>Begin with a few contrasting meze</h2><p>Meze are small dishes intended to be shared. A useful starting combination includes something creamy, something bright or spicy, and a vegetable preparation. Yogurt, chickpeas, eggplant, peppers, herbs, olive oil and lemon appear in many Turkish meze traditions. The contrast matters more than ordering a long list.</p><p>Use bread to move between flavors, but pace the table. Two or three meze can introduce the meal without crowding out the warm dishes that follow. Review the <a href=\"/menu\">current Turquaz menu</a> because dishes and availability can change.</p><h2>Add warmth from the oven or grill</h2><p>Pide, kebabs, kofte and vegetable plates create a natural second stage. Pide is a boat-shaped flatbread with a crisp edge and a tender center. Kebab describes a family of preparations rather than one recipe, while kofte generally refers to seasoned meat shaped for cooking. A mixed table can pair one substantial warm dish with vegetables, grains or salad.</p><h3>Order for the whole table</h3><p>Ask what everyone enjoys before ordering. A party that wants to explore can share several items, while a guest with a specific preference may want an individual plate. Ingredient and dietary questions should always be confirmed directly with the restaurant because recipes and kitchen practices can change.</p><h2>Finish with sweetness and a hot drink</h2><p>Baklava or another pastry brings texture and sweetness after savory food. Turkish coffee is concentrated and served in a small cup; Turkish tea is lighter and can extend the conversation. Neither needs to be rushed.</p><h2>A simple first-order plan</h2><ol><li>Choose two or three contrasting meze.</li><li>Add bread or a baked specialty.</li><li>Select a grilled, vegetable or grain-based main dish.</li><li>Share dessert if the table still has room.</li><li>End with Turkish tea or coffee.</li></ol><p>There is no single correct first order. The best introduction fits the people at the table. <a href=\"/#reservation\">Reserve a table at Turquaz</a> and use the live menu to plan the meal around current choices.</p>"}]',
  'published',
  'First Turkish Meal: What to Order | Turquaz SF',
  'Plan your first Turkish meal with meze, pide, grilled dishes, dessert, coffee and tea at Turquaz in San Francisco.',
  'https://www.turquazsf.com/assets/images/dish-feast.jpeg',
  'Shared Turkish meal with meze, bread, vegetables and grilled dishes at Turquaz',
  'what to order first Turkish meal',
  'Turquaz',
  '2026-08-26T16:00:00.000Z',
  '2026-08-26T16:00:00.000Z',
  '2026-08-26T16:00:00.000Z'
),
(
  '88888888-8888-4888-8888-888888888888',
  'blog',
  'turkish-meze-guide',
  'Turkish Meze Guide: How to Build a Shared Table',
  'Learn how creamy, bright, smoky, spicy and fresh Turkish meze work together at a shared table.',
  '[{"type":"html","html":"<p>Meze turn ordering into a shared experience. Small dishes arrive together, allowing each person to combine flavors and move through the meal at a comfortable pace. Across Turkish cooking, meze can feature vegetables, yogurt, legumes, herbs, seafood, cheese, grains and olive oil. The exact selection varies by region, season and kitchen.</p><h2>Think in contrasts, not quantity</h2><p>A balanced meze order does not need every dish on the menu. Begin by combining different temperatures, textures and flavor profiles. A creamy dip can sit beside a crisp salad. A smoky eggplant preparation can balance a bright tomato or pepper dish. Pickles or lemon can refresh the palate between richer bites.</p><h3>Creamy and cooling</h3><p>Yogurt-based dishes and hummus bring body to the table. Their mild richness can soften heat and pair naturally with bread. Some preparations include garlic, herbs, tahini or olive oil, so guests with ingredient concerns should ask the team about the current recipe.</p><h3>Vegetable-forward and bright</h3><p>Eggplant, peppers, tomatoes, cucumbers, greens and legumes create variety without making the table feel heavy. Roasting can develop sweetness and smoke; fresh herbs and acidity can keep a dish lively. Turkish cooking offers many vegetable preparations, but availability is specific to the current menu.</p><h2>Use bread with intention</h2><p>Bread is both part of the meal and a way to experience the texture of a meze. Tear a manageable piece, pair it with one or two flavors, and return to another dish. Ordering bread gradually can help the table keep space for warm plates.</p><h2>Move from meze to the rest of the meal</h2><p>Meze can be the beginning of dinner or the center of a lighter meal. For a fuller table, follow with pide, a grilled plate, vegetables, rice or bulgur. The transition works best when the later dishes add something new rather than repeating the same flavor profile.</p><h2>Example combinations</h2><table><thead><tr><th>Table mood</th><th>Starting approach</th></tr></thead><tbody><tr><td>Fresh and light</td><td>Vegetable dishes, herbs, acidity and bread</td></tr><tr><td>Rich and comforting</td><td>Yogurt, legumes, roasted vegetables and a warm plate</td></tr><tr><td>Broad introduction</td><td>One creamy, one bright and one smoky or spicy meze</td></tr></tbody></table><p>Explore the <a href=\"/menu\">Turquaz menu</a> to see the current selection, then <a href=\"/#reservation\">reserve a table</a> if you are planning a shared meal in San Francisco.</p>"}]',
  'published',
  'Turkish Meze Guide for a Shared Table | Turquaz',
  'Learn how to order Turkish meze by balancing creamy, bright, smoky, spicy and vegetable-forward dishes for a shared table.',
  'https://www.turquazsf.com/assets/images/dish-1.jpeg',
  'Colorful Turkish meze served in small dishes for sharing at Turquaz',
  'Turkish meze guide',
  'Turquaz',
  '2026-08-27T15:00:00.000Z',
  '2026-08-27T15:00:00.000Z',
  '2026-08-27T15:00:00.000Z'
),
(
  '99999999-9999-4999-8999-999999999999',
  'blog',
  'pide-vs-lahmacun',
  'Pide vs. Lahmacun: Two Turkish Oven Traditions',
  'Compare the shape, dough, toppings, texture and serving style of Turkish pide and lahmacun.',
  '[{"type":"html","html":"<p>Pide and lahmacun are both baked Turkish specialties, but they create different eating experiences. The easiest distinction is visual: pide is generally shaped like a long, open boat, while lahmacun is thin, round and covered edge to edge with a finely chopped savory topping. Their dough, texture and serving styles also differ.</p><h2>What is Turkish pide?</h2><p>Pide uses a shaped dough with raised edges that hold its toppings. The center can remain tender while the rim develops color and structure in the oven. Toppings vary and may include cheese, vegetables, egg or seasoned meat. The result is substantial enough to anchor a meal but works especially well when several varieties are sliced and shared.</p><p>The word pide can refer to different breads and regional preparations in Turkey, so one restaurant version should not be treated as the only definition. At a restaurant, the menu description is the best guide to its size and toppings.</p><h2>What is lahmacun?</h2><p>Lahmacun begins with a thinner round of dough and a finely distributed topping commonly built from minced meat, tomato, pepper, herbs and seasoning. It bakes quickly and develops a crisp, flexible texture. Diners often add fresh herbs, vegetables or lemon and then fold or roll each portion.</p><p>Although lahmacun is sometimes casually described as Turkish pizza, that shorthand misses its thinner construction, finely spread topping and customary accompaniments. It is useful as an introduction, not a complete definition.</p><h2>How texture changes the meal</h2><p>Pide offers a stronger contrast between its shaped crust and filled center. Lahmacun distributes flavor in a thinner layer and is often brightened at the table. Pide may feel like a centerpiece, while lahmacun can work as a starter, snack or shared component alongside meze and salad.</p><h2>Which one should you order?</h2><ul><li>Choose pide when you want a thicker, shaped bread with distinct toppings.</li><li>Choose lahmacun when you want something thin, crisp and easy to brighten with herbs or lemon.</li><li>Order both for the table when you want to compare two oven traditions directly.</li></ul><p>Selections can change, so check the <a href=\"/menu\">live Turquaz menu</a> rather than assuming a particular topping is available. Pair either option with meze or salad, and <a href=\"/#reservation\">reserve ahead</a> when organizing a group meal.</p>"}]',
  'published',
  'Pide vs Lahmacun: Turkish Flatbreads Explained',
  'Compare Turkish pide and lahmacun by shape, dough, toppings, texture and serving style before planning your meal at Turquaz.',
  'https://www.turquazsf.com/assets/images/dish-pastries.jpeg',
  'Freshly baked Turkish flatbread and pastries displayed at Turquaz',
  'pide vs lahmacun',
  'Turquaz',
  '2026-08-27T16:00:00.000Z',
  '2026-08-27T16:00:00.000Z',
  '2026-08-27T16:00:00.000Z'
),
(
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  'blog',
  'turkish-desserts-baklava-guide',
  'Turkish Desserts and Baklava: A Practical Guide',
  'Explore baklava, pastry, nuts, syrup and the role of Turkish coffee or tea at the end of a meal.',
  '[{"type":"html","html":"<p>Turkish desserts range from crisp layered pastries to milk-based sweets, fruit preserves and confections. Baklava is the most widely recognized example, but even baklava is not one fixed recipe. The nuts, shape, syrup, size and regional style can all vary.</p><h2>How baklava gets its texture</h2><p>Baklava relies on many thin layers of dough, fat, nuts and syrup. Good texture comes from maintaining separation between the layers during baking and balancing crisp pastry with the added syrup. Pistachios and walnuts are common, though the nut depends on the style and kitchen.</p><p>The pastry is rich, so a small piece can provide a complete finish to a meal. Its sweetness also pairs naturally with a drink that is not itself heavily sweetened.</p><h2>Why Turkish coffee works with dessert</h2><p>Turkish coffee is made from very finely ground coffee and served unfiltered in a small cup. Its concentration and roasted character contrast with syrup and pastry. Sip slowly and allow the grounds to remain at the bottom of the cup.</p><p>Turkish tea offers a different pairing. It can feel lighter and extend the table after the food is finished. Guests can adjust sweetness according to preference.</p><h2>Beyond one famous pastry</h2><p>Turkish dessert traditions also include milk puddings, semolina-based sweets, fruit and pumpkin desserts, lokum, cookies and other pastries. Restaurants select from this broad tradition according to their kitchen, season and service. The current menu is the reliable source for what is available on a given visit.</p><h2>How to share dessert</h2><ol><li>Choose one dessert for every two or three guests when the table wants only a taste.</li><li>Add coffee or tea and compare how each changes the sweetness.</li><li>Ask about nuts and other allergens before ordering.</li><li>Take time with the final course rather than treating it as an afterthought.</li></ol><h2>Plan the full meal</h2><p>If dessert matters to your visit, avoid over-ordering at the start. A progression from meze to a warm dish and then pastry creates contrast without requiring a very large portion at any stage. Browse the <a href=\"/menu\">current menu</a> for available sweets and drinks. For breakfast, dinner or a gathering with friends, <a href=\"/#reservation\">reserve a table at Turquaz</a> in San Francisco.</p>"}]',
  'published',
  'Turkish Desserts and Baklava Guide | Turquaz SF',
  'Explore Turkish baklava, layered pastry, nuts, syrup and traditional coffee or tea pairings with Turquaz in San Francisco.',
  'https://www.turquazsf.com/assets/images/gallery-5.jpeg',
  'Turkish baklava and pastries prepared for dessert at Turquaz in San Francisco',
  'Turkish desserts and baklava',
  'Turquaz',
  '2026-08-27T17:00:00.000Z',
  '2026-08-27T17:00:00.000Z',
  '2026-08-27T17:00:00.000Z'
);
