UPDATE content_entries
SET seo_title = 'Turkish Breakfast San Francisco Guide | Turquaz',
    seo_description = 'Explore Turkish breakfast in San Francisco, from shared cheeses, olives and eggs to pastries, tea and planning a table at Turquaz.',
    body_json = json_insert(body_json, '$[#]', json_object('type', 'html', 'html', '<h2>How to plan a Turkish breakfast table</h2><p>Begin by balancing savory, fresh and sweet elements rather than treating breakfast as a list of separate courses. Cheese, olives, tomatoes and cucumbers create a fresh base. Eggs or a warm pastry add substance, while honey or preserves provide contrast. Tea connects the meal and makes it easy to slow down between bites.</p><p>For a group, order enough variety for everyone to taste without filling the table immediately. Ask about current pastry fillings and ingredients, especially when a guest has an allergy or dietary restriction. Recipes and availability can change, so the team and the <a href="/menu">live menu</a> are the reliable sources for the day.</p><h2>Breakfast timing and reservations in San Francisco</h2><p>A shared breakfast often takes longer than coffee and a single pastry. Allow time for dishes to arrive, tea to be refreshed and the table to explore different combinations. Confirm current opening hours before traveling, particularly around holidays. When meeting friends, family or colleagues, a <a href="/#reservation">breakfast reservation</a> helps the restaurant prepare for the party and gives the group a clear meeting time.</p>')),
    updated_at = '2026-08-27T23:40:00.000Z'
WHERE id = '11111111-1111-4111-8111-111111111111';

UPDATE content_entries
SET seo_description = 'Explore Turkish meze, kebabs, pide, grains, vegetables, yogurt and pastries, with practical tips for building a meal at Turquaz.',
    body_json = json_insert(body_json, '$[#]', json_object('type', 'html', 'html', '<h2>How to build a balanced Turkish meal</h2><p>Start with contrast. A creamy or yogurt-based meze can sit beside something acidic, herbaceous or spicy. Add bread for texture, then choose a warm dish that brings a different cooking method, such as baking or grilling. Rice, bulgur, salad or a vegetable plate can round out the table without repeating the same flavors.</p><p>Guests do not need to order every category at once. Two or three meze and one warm dish may suit a smaller table, while a larger group can compare more preparations. Review the <a href="/menu">current menu and prices</a> before visiting because selections can change.</p><h2>Questions worth asking at the restaurant</h2><p>Turkish cuisine is broad, and a dish name alone does not describe every ingredient or regional variation. Ask about heat level, nuts, dairy, gluten and preparation when those details affect your meal. The restaurant team can describe the current recipe more accurately than a general guide.</p><p>For a first visit, tell the team whether the table wants a quick individual meal or a longer shared experience. If several guests plan to explore the menu together, <a href="/#reservation">reserve a table</a> and allow time for dishes to be shared in stages.</p>')),
    updated_at = '2026-08-27T23:41:00.000Z'
WHERE id = '22222222-2222-4222-8222-222222222222';

UPDATE content_entries
SET seo_title = 'Turkish Coffee San Francisco Guide | Turquaz',
    body_json = json_insert(body_json, '$[#]', json_object('type', 'html', 'html', '<h2>How to enjoy Turkish coffee</h2><p>Turkish coffee is served unfiltered, so it rewards a slower approach. Take small sips from the upper portion of the cup and stop when the settled grounds begin to reach the rim. Water can refresh the palate before or after the coffee. Sweetness is traditionally chosen during preparation, although the available service style depends on the kitchen.</p><p>The drink is concentrated but small. It can follow a full meal, accompany a pastry or create a short pause on its own. Ask the team about the current coffee and dessert choices rather than assuming every traditional pairing is available.</p><h2>Tea at breakfast and around the table</h2><p>Turkish tea suits a different rhythm. Its lighter body makes it easy to drink across breakfast or during a conversation. Sharing a pot or accepting a refill is part of the social experience, but each guest can choose strength and sweetness according to taste.</p><p>Browse the <a href="/menu">Turquaz menu</a> for current drinks and pastries. If coffee or tea is part of a longer meal with friends, <a href="/#reservation">reserve a table</a> and give the group time to enjoy the final cup without rushing.</p><h2>Choose the right moment for each drink</h2><p>Tea can accompany breakfast or a long conversation, while coffee often creates a distinct closing moment after food. A table may enjoy both at different stages. Confirm current service hours and drink availability before making a special trip.</p>')),
    updated_at = '2026-08-27T23:42:00.000Z'
WHERE id = '33333333-3333-4333-8333-333333333333';

UPDATE content_entries
SET seo_description = 'Plan Mission District dining in San Francisco with practical guidance for timing, transit, group meals, reservations and Turquaz menu choices.',
    body_json = json_insert(body_json, '$[#]', json_object('type', 'html', 'html', '<h2>Getting to 1198 Mission Street</h2><p>Turquaz is on Mission Street near the Civic Center side of the corridor. San Francisco transit, traffic, parking rules and event schedules can change, so check a current map and transportation source on the day of the visit. Build extra time into the plan when the group is arriving from different neighborhoods or attending a nearby performance or event.</p><p>Share the exact address with every guest instead of relying only on a neighborhood name. A clear meeting point prevents confusion because the Mission corridor extends across a large part of the city.</p><h2>Match the order to the occasion</h2><p>A work lunch may call for individual bowls, salads or grilled plates. A relaxed dinner can begin with meze and bread before moving to warm dishes. Families and groups may prefer several items at the center of the table. Check the <a href="/menu">live menu</a> before deciding because dishes and prices may change.</p><h2>Make the day easier for a group</h2><p>Collect dietary questions early, choose a realistic arrival time and decide whether the group wants a quick meal or an extended gathering. A <a href="/#reservation">reservation at Turquaz</a> helps establish the plan. For more than 15 guests or a special event, contact the restaurant directly to discuss current options.</p>')),
    updated_at = '2026-08-27T23:43:00.000Z'
WHERE id = '44444444-4444-4444-8444-444444444444';

UPDATE content_entries
SET seo_title = 'Turkish Restaurant San Francisco | Turquaz',
    body_json = json_insert(body_json, '$[#]', json_object('type', 'html', 'html', '<h2>Choose a meal for the time of day</h2><p>Breakfast can center on pastries, eggs, cheese, olives, vegetables, tea and coffee. Lunch may suit bowls, salads, flatbreads or grilled plates, while dinner gives a table more time to share meze and warm dishes. Current service hours and menu availability should be confirmed before traveling, especially on holidays.</p><p>The <a href="/menu">Turquaz menu</a> is the best source for current dishes and prices. General cuisine guides can explain traditions, but they cannot confirm what a restaurant is serving on a particular day.</p><h2>Plan for dietary and ingredient questions</h2><p>Turkish and Mediterranean cooking uses a broad range of grains, dairy, nuts, legumes, vegetables, herbs and meats. Guests with allergies or dietary restrictions should speak with the restaurant about current recipes and kitchen practices. Avoid relying on assumptions based only on a dish name.</p><h2>Meeting friends, family or colleagues</h2><p>Shared meze and bread can create an easy beginning for a social meal, followed by grilled, baked or vegetable dishes. Decide whether the table prefers sharing or individual plates and communicate any timing constraints when arriving.</p><p>Use the online form to <a href="/#reservation">reserve for up to 15 guests</a>. Larger parties, catering questions and special arrangements should be discussed directly with the restaurant so the team can explain current possibilities.</p><h2>Before traveling to Mission Street</h2><p>Confirm current hours, transit and parking information on the day of the visit. Share the full 1198 Mission Street address with the group and allow extra arrival time when nearby events affect traffic.</p>')),
    updated_at = '2026-08-27T23:44:00.000Z'
WHERE id = '55555555-5555-4555-8555-555555555555';

UPDATE content_entries
SET body_json = json_insert(body_json, '$[#]', json_object('type', 'html', 'html', '<h2>Quantities, timing and service details</h2><p>A useful catering request includes the event date, service time, delivery or pickup preference, estimated guest count and location. Explain whether the food is the complete meal or one part of a larger event. This context helps the restaurant discuss quantities and menu combinations without guessing.</p><p>Ask how dishes should be held, reheated or served and whether utensils, labels or serving equipment are included. Confirm final counts and logistics through the active ordering channel because packages, minimums, prices and delivery areas can change.</p><h2>Design a menu for varied preferences</h2><p>A broad spread can combine vegetable meze, salad, bread, grains and warm dishes. Collect allergy and dietary questions from attendees before placing the order, then confirm ingredients and kitchen practices directly with the restaurant. A dish name or general cuisine description is not an allergy guarantee.</p><p>Explore the <a href="/menu">current Turquaz menu</a> for inspiration, but use the restaurant or linked catering platform to confirm what can be prepared at scale. For an in-restaurant gathering of up to 15 guests, use the <a href="/#reservation">online reservation form</a>. Contact the team directly for larger groups and event-specific needs.</p><h2>Confirm the final event plan</h2><p>Recheck the guest count, address, contact person and service time before the order deadline. Keep one organizer available on the event day to answer delivery or setup questions and communicate any building access instructions.</p>')),
    updated_at = '2026-08-27T23:45:00.000Z'
WHERE id = '66666666-6666-4666-8666-666666666666';

UPDATE content_entries
SET seo_title = 'What to Order First Turkish Meal Guide | Turquaz',
    seo_description = 'Learn what to order for a first Turkish meal, from contrasting meze and bread to grilled dishes, dessert, coffee and tea at Turquaz.',
    body_json = json_insert(body_json, '$[#]', json_object('type', 'html', 'html', '<h2>Adjust the order for party size</h2><p>Two guests can learn a great deal from a few contrasting meze and one warm dish. A larger table can compare more preparations, but ordering in stages prevents food from arriving faster than the group can enjoy it. Ask the team which items are naturally portioned for sharing.</p><p>Before ordering, mention allergies and dietary restrictions and confirm the current ingredients. A broad cuisine guide cannot replace information from the kitchen. Use the <a href="/menu">current menu</a> to identify questions, then <a href="/#reservation">reserve a table</a> when the first meal is part of a planned gathering.</p>')),
    updated_at = '2026-08-27T23:46:00.000Z'
WHERE id = '77777777-7777-4777-8777-777777777777';

UPDATE content_entries
SET body_json = json_insert(body_json, '$[#]', json_object('type', 'html', 'html', '<h2>Meze for different table sizes</h2><p>For two people, two or three small plates can provide contrast without replacing the rest of the meal. Four or more guests can explore a wider range, but it is still useful to order in stages. Ask which dishes are cold, warm, mild or spicy and let those answers guide the sequence.</p><p>Ingredient questions matter because recipes can include dairy, sesame, nuts, gluten or other allergens. Confirm current preparation directly with the restaurant. Review the <a href="/menu">live menu</a>, and <a href="/#reservation">reserve a table</a> when the shared meal is tied to a specific time or gathering.</p>')),
    updated_at = '2026-08-27T23:47:00.000Z'
WHERE id = '88888888-8888-4888-8888-888888888888';

UPDATE content_entries
SET body_json = json_insert(body_json, '$[#]', json_object('type', 'html', 'html', '<h2>Pairing each bread with the table</h2><p>Pide can anchor a spread with meze, salad or grilled vegetables because its thicker shaped crust has more presence. Lahmacun often works well with fresh herbs, vegetables and lemon, creating a lighter contrast. Sharing both lets guests compare texture before choosing another warm dish.</p><p>Specific toppings and accompaniments vary, and neither item should be assumed available without checking. Consult the <a href="/menu">current Turquaz menu</a> and ask about ingredients when allergies or dietary restrictions apply. For a planned comparison with friends, <a href="/#reservation">reserve a table</a> and order at a pace that lets both breads arrive with their intended texture.</p>')),
    updated_at = '2026-08-27T23:48:00.000Z'
WHERE id = '99999999-9999-4999-8999-999999999999';

UPDATE content_entries
SET body_json = json_insert(body_json, '$[#]', json_object('type', 'html', 'html', '<h2>Ordering dessert with allergies in mind</h2><p>Baklava commonly contains tree nuts, wheat and dairy ingredients, but recipes and handling practices differ. Guests with allergies should ask the restaurant about the current dessert and kitchen procedures rather than relying on a general description. The same care applies to other pastries and confections.</p><p>Choose dessert after seeing how much the table has ordered, or plan from the beginning to leave room. Check the <a href="/menu">current menu</a> for available sweets and drinks. A <a href="/#reservation">table reservation</a> can make a relaxed dessert-and-coffee finish easier when dining with a group.</p>')),
    updated_at = '2026-08-27T23:49:00.000Z'
WHERE id = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
